# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_v2', '0003_account_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
