# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_v2', '0004_auto_20190122_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
