# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_v2', '0005_auto_20190122_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
