# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_v2', '0009_auto_20190123_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
