# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20190121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
