# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
            ],
        ),
    ]
