# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20190121_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
