# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20190123_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(b'Credit', b'Credit'), (b'Debit', b'Debit')], default=b'Credit', max_length=20),
            preserve_default=False,
        ),
    ]
